### The state variable that the langgraph nodes are based on

from typing import List, Optional, TypedDict
from app.schemas.chunk import Chunk

class QueryState(TypedDict):
    # 1. The original user input (user query)
    question: str
    
    # 2. Extracted intents (Populated by the Intent Node)
    # Optimized query for Chroma (generated by LLM)
    search_query: str          
    
    # e.g., "django", "angular", "react"
    technology: str            

    version_major: Optional[int]
    version_minor: Optional[int]
    version_patch: Optional[int]
    version_operator: str

    current_version_major: Optional[int]
    current_version_minor: Optional[int]
    current_version_patch: Optional[int]
    target_version_major: Optional[int]
    target_version_minor: Optional[int]
    target_version_patch: Optional[int]

    is_breaking: Optional[bool]
    
    # 3. Retrieval results (Populated by the Retrieval Node)
    retrieved_chunks: List[Chunk]
    
    # Retrieved chunk distance/score
    distances: Optional[List[float]]
    
    # 4. Final output (Populated by the Generation Node)
    answer: str

""" 
Data flows linearly (or cyclically) through the QueryState.
Intent/Router Node mutates the state (adds search parameters).
Retrieval Node reads parameters, fetches data, mutates state (adds chunks).
Reasoning Node evaluates chunks against the intent.
Conditional Edge decides the next step based on the reasoning
 (e.g., if relevant -> Generate; if irrelevant -> Rewrite Query or Fallback).
Generation Node finally responds back to the user.
"""